### ISSUE TITLE
Atom project.

### ISSUE THREAD

**Issue by AtomSnippets** [zargony/dotfiles#2]
Hello,

Seems like you're active in this project but not the Rust package.
I have a pull request there to include some snippets but there are some snippets here: https://github.com/honza/vim-snippets which I would like to have included as atom snippets.
These are Vim snippets, unfortunately I don't have any experience with VimL but it seems like you do if I look at your folders. So my request: would you like to convert some snippets from Vim into atom snippets?

**Comment by zargony** [comment]
Hi,
thanks for your contribution and sorry for the delay. Unfortunately work and life often keeps me busy and I can't be active in all projects all the time. Also I'm not a big fan of snippets. I usually don't use many of them. So I'm probably not the right person to ask for creating more snippets ;)
